FROM SOURCE_IMAGE as cayo

ARG IMAGE_VERSION_ARG
ARG KERNEL_NAME_ARG
#ifdef CI_SETX
ARG CI=1
#endif /* CI_SETX */



COPY extensions/samba/ /usr/share/cayo/extensions/samba/
RUN rm -rf /usr/share/cayo/extensions/samba/rootfs
RUN rm -rf /usr/share/cayo/extensions/samba/rpms

RUN ls -la /usr/share/cayo/extensions/samba/